
ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS modelo TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ano INTEGER,
  ADD COLUMN IF NOT EXISTS renavam TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS chassi TEXT NOT NULL DEFAULT '';
