// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akklvkbbclpwruqegqsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFra2x2a2JiY2xwd3J1cWVncXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1ODE2NzAsImV4cCI6MjA4ODE1NzY3MH0.ApYDrkKfiaGjsvtp86ygejTEBYjkHJH4I7EOJgIukEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});